---
title: Research
toc: true
---

## Job Market Paper

### Student Loan on Labor Market Outcomes: Evidence from the Unlucky Generation in the Netherlands

**Latest draft available upon request**

Abstract: This paper investigates the causal effect of student debt on early-career labor market outcomes. I exploit a 2015 Dutch reform from a more grant-reliant system to a more loan-based regime where a universal student grant was removed, which created a sharp, exogenous increase in debt for cohorts that started university from 2025. Using rich administrative data, I employ a difference-in-differences strategy that takes advantage of variation in study grant loss, which determined eligibility for offset supplementary grants. I find that higher student debt did not lead to a significant reduction in university enrollment and completion. However, it did cause a notable decrease in earnings and an increase in the likelihood of securing permanent employment one year after graduation. Higher debt is associated with more part-time work during university, shorter job-searching spell, and reduced enrollment in master's programs. These findings are consistent with a "debt aversion" channel, where the psychological burden of debt harms human capital accumulation after undergraduate studies and the realization of their accumulated human capital.

## Work in Progress
### Bankruptcy Rules and Innovation [View Slides](files/Presentation_v5.pdf){target="_blank"}

Abstract: Innovation is a crucial driver of economic growth, but investment in innovation is also risky. Limited liability can stimulate innovation by providing insurance against downside risk, but it can also stifle it if agency problems reduce credit supply. We use the passage of the first permanent federal bankruptcy code in 1898 as a natural experiment. We first introduce a model that shows the effects of bankruptcy law on innovation are ambiguous, depending on the pre-existing leniency of state-level laws protecting borrowers’ assets against creditors. Using a difference-in-differences method, we test this prediction by studying how the change in limited liability translates to changes in patenting activity by independent inventors, exploiting variation in pre-existing state-level bankruptcy codes and the moderating effect of homestead exemptions. We found that increasing debtor protection leads to an increase in innovation in states with low homestead exemptions but a reduction in patenting in states with high homestead exemptions. Conversely, increasing creditor protection exerts a positive effect only in states with low homestead exemptions. We further explore potential mechanisms by examining how inventor characteristics (e.g., proxies for ex-ante wealth from U.S. Census data) interact with the observed changes in innovation.

### Supply Chain Uncertainty on Corporate Innovation

### How Technology Progress Shapes Venture Capital Hiring?
